# Generated by Django 3.1.1 on 2023-11-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_song_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='songrating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        #migrations.AddField(
        #    model_name='songrating',
        #    name='song',
        #    field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Songs.song'),
        #),
    ]
