# Generated by Django 3.1.1 on 2023-11-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0002_auto_20231120_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrating',
            name='Song',
        ),
    ]
