# Generated by Django 3.1.1 on 2023-11-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0003_remove_songrating_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrating',
            name='Song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Songs.song'),
        ),
    ]
